(function(){
var Y=window.YAD,$=function(s,r){return (r||document).querySelector(s)},$$=function(s,r){return Array.prototype.slice.call((r||document).querySelectorAll(s))};
var fm=function(n){return n?'PKR '+Number(n).toLocaleString('en-US'):'Price on request'},num=function(n){return Number(n).toLocaleString('en-US')};
function wl(m){return 'https://wa.me/'+Y.wa+'?text='+encodeURIComponent(m)}
var WAI='<svg viewBox="0 0 32 32"><path d="M16 3C9 3 3.4 8.6 3.4 15.5c0 2.3.6 4.4 1.7 6.3L3 29l7.4-2c1.8 1 3.8 1.5 5.6 1.5 7 0 12.6-5.6 12.6-12.5S23 3 16 3zm6.3 17.6c-.3.8-1.6 1.5-2.2 1.6-.6.1-1.3.1-2.1-.1-.5-.2-1.1-.4-1.9-.7-3.3-1.4-5.4-4.7-5.6-4.9-.2-.2-1.3-1.7-1.3-3.2s.8-2.3 1.1-2.6c.3-.3.6-.4.8-.4h.6c.2 0 .5-.1.7.5l1 2.4c.1.2.1.4 0 .6l-.4.6-.5.6c-.2.2-.3.4-.1.7.2.3.9 1.5 2 2.4 1.4 1.2 2.5 1.6 2.9 1.8.3.2.5.1.7-.1l.9-1.1c.2-.3.4-.2.7-.1l2.2 1.1c.3.1.5.2.6.3.1.2.1.8-.2 1.5z"/></svg>';
var soc=Y.social.map(function(s){return '<a href="'+s[2]+'" target="_blank" rel="noopener" aria-label="'+s[1]+'">'+s[0]+'</a>'}).join('');
var P=Y.products,by={};P.forEach(function(p){by[p.id]=p});var pg=document.body.dataset.page,QS=new URLSearchParams(location.search);
function grp(cat){var s=[];P.forEach(function(p){if(p.cat===cat&&s.indexOf(p.series)<0)s.push(p.series)});return s}
function seriesLinks(){return Y.cats.map(function(c){return '<div><h5>'+c+'</h5>'+grp(c).map(function(s){return '<a href="shop.html?series='+encodeURIComponent(s)+'">'+s+'</a>'}).join('')+'</div>'}).join('')}
var abt=[['about.html','About YAD'],['contact.html','Contact']],svc=[['service.html#warranty','After-sales Service'],['service.html#faq','FAQ']];
var lk=function(a){return a.map(function(x){return '<a href="'+x[0]+'">'+x[1]+'</a>'}).join('')};
$('#hdr').innerHTML='<header class="hd"><div class="wrap"><a class="brand" href="index.html"><img src="images/logo.svg" alt="YAD Electric Vehicles"></a><nav class="dn"><div class="dd"><a class="'+(pg==='shop'||pg==='product'?'on':'')+'" href="shop.html">Models</a><div class="mega big">'+seriesLinks()+'</div></div><div class="dd"><a class="'+(pg==='about'||pg==='contact'?'on':'')+'" href="about.html">About Us</a><div class="mega">'+lk(abt)+'</div></div><div class="dd"><a class="'+(pg==='service'?'on':'')+'" href="service.html">Service</a><div class="mega">'+lk(svc)+'</div></div><a class="'+(pg==='store'?'on':'')+'" href="find-store.html">Find a Store</a><a class="'+(pg==='compare'?'on':'')+'" href="compare.html">Compare</a></nav><div class="acts"><a class="wab" target="_blank" rel="noopener" href="'+wl('Assalam o Alaikum YAD')+'" aria-label="WhatsApp">'+WAI+'<span>WhatsApp</span></a><button class="bur" aria-label="Menu"><i></i><i></i><i></i></button></div></div></header><div class="ovl"></div><aside class="drw"><button class="x" aria-label="Close">✕</button><a class="l" href="index.html">Home</a><details><summary class="l">Models</summary>'+seriesLinks()+'</details><details><summary class="l">About Us</summary>'+lk(abt)+'</details><details><summary class="l">Service</summary>'+lk(svc)+'</details><a class="l" href="find-store.html">Find a Store</a><a class="l" href="compare.html">Compare</a><div class="soc">'+soc+'</div></aside>';
$('#ftr').innerHTML='<footer><div class="wrap"><div><img src="images/logo.svg" alt="YAD"><p>Yi An Da Hubei Automobile Co (Pvt) Ltd</p><p>Ride Smart · Ride Green · Ride YAD</p></div><div><h4>Explore</h4><a href="shop.html">Models</a><a href="compare.html">Compare</a><a href="about.html">About</a><a href="service.html">Service</a><a href="find-store.html">Find a Store</a><a href="contact.html">Contact</a></div><div><h4>Visit</h4><p>91-B, Sundar Small Industries Estate II, Lahore</p><p>Mehboob Jafar: +92 300 6591 354</p></div><div><h4>Follow</h4><div class="soc">'+soc+'</div></div></div></footer><a class="fab" href="'+wl('Assalam o Alaikum YAD')+'" target="_blank" rel="noopener" aria-label="WhatsApp">'+WAI+'</a>';
var d=$('.drw'),o=$('.ovl');function menu(v){d.classList.toggle('open',v);o.classList.toggle('open',v);document.body.classList.toggle('lock',v)}
$('.bur').onclick=function(){menu(true)};$('.drw .x').onclick=function(){menu(false)};o.onclick=function(){menu(false)};$$('.drw a').forEach(function(a){a.addEventListener('click',function(){menu(false)})});
function uniq(a){return a.filter(function(x,i){return x&&a.indexOf(x)===i})}
function vv(p,k){return uniq(p.vars.map(function(v){return k==='Price'?(v.pr?fm(v.pr):''):k==='Battery'?v.bat:k==='Motor'?v.mot:''})).join(' / ')}
function minp(p){var a=p.vars.map(function(v){return v.pr}).filter(Boolean);return a.length?Math.min.apply(null,a):0}
function pr(p){var m=minp(p);return m?(p.vars.length>1?'From ':'')+fm(m):'Price on request'}
function find(p,k){if(k==='Price'||k==='Battery'||k==='Motor')return vv(p,k)||null;var r=p.ex.filter(function(x){return x[0]===k})[0];return r?r[1]:null}
function spec(p){var r=[];['Price','Battery','Motor'].forEach(function(k){var v=vv(p,k);if(v)r.push([k,v])});return r.concat(p.ex)}
function sw(p){return '<div class="sw2">'+p.colors.map(function(c){return '<span><i style="background:linear-gradient(135deg,'+c[1]+' 50%,'+c[2]+' 50%)"></i>'+c[0]+'</span>'}).join('')+'</div>'}
function card(p){var im=p.imgs.length?'images/p/'+p.imgs[0]+'.webp':'images/placeholder.svg';return '<a class="pc" data-cat="'+p.cat+'" data-series="'+p.series+'" data-name="'+p.n.toLowerCase()+'" data-price="'+minp(p)+'" href="product.html?id='+p.id+'"><div class="pim"><img loading="lazy" src="'+im+'" alt="'+p.n+'"></div><div class="pin"><span class="tg">'+p.series+'</span><h3>'+p.n+'</h3><p class="mt">'+(vv(p,'Battery')?vv(p,'Battery').split(' / ').pop()+' · '+vv(p,'Motor').split(' / ').pop():'Specs on request')+'</p><b class="pr">'+pr(p)+'</b></div></a>'}
function calc(box,p0){var C=Y.calc;box.innerHTML='<div class="calc"><div class="cl"><div class="tag">Savings calculator</div><h2>Buying YAD is money in the bank</h2><p>Tell us how far you ride every day. We estimate your monthly saving against a petrol scooter.</p><label>Model</label><select id="cm">'+P.map(function(p){return p.vars.filter(function(v){return v.bat}).map(function(v,i){return '<option value="'+p.id+'|'+p.vars.indexOf(v)+'"'+(p.id===p0.id&&i===0?' selected':'')+'>'+v.n+'</option>'}).join('')}).join('')+'</select><label>Daily distance: <b id="dkv">30</b> km</label><input id="dk" type="range" min="5" max="120" value="30"><div class="kvs"><div><label>Petrol PKR/litre</label><input id="cp" type="number" value="'+C.petrol+'"></div><div><label>Petrol bike km/litre</label><input id="ck" type="number" value="'+C.kmpl+'"></div><div><label>Electricity PKR/unit</label><input id="cu" type="number" value="'+C.unit+'"></div><div><label>YAD range km (full charge)</label><input id="cr" type="number" value="60"></div></div></div><div class="cr"><div class="row3"><div><span>Petrol, monthly</span><b id="o1">0</b></div><div><span>YAD, monthly</span><b id="o2">0</b></div></div><div class="save"><span>Monthly saving</span><b id="o3">0</b><span>Yearly saving</span><b id="o4">0</b></div><p class="note">Estimate only. Change the values to match your own petrol price, electricity tariff and riding.</p><a class="btn" id="cs" href="contact.html">Schedule a ride</a></div></div>';
 function cur(){var a=$('#cm').value.split('|');return {p:by[a[0]],v:by[a[0]].vars[+a[1]]}}function setR(){var c=cur(),r=parseFloat((find(c.p,'Range')||'').replace(/[^\d.]/g,'').split('.')[0]);$('#cr').value=r||60}
 function upd(){var c=cur(),p=c.v,m=p.bat.match(/(\d+)V\s*(\d+)Ah/),kwh=m?m[1]*m[2]/1000:2,km=+$('#dk').value,rng=+$('#cr').value||60,pet=km*30*$('#cp').value/$('#ck').value,el=km*30*kwh/rng*$('#cu').value;$('#dkv').textContent=km;$('#o1').textContent='PKR '+num(Math.round(pet));$('#o2').textContent='PKR '+num(Math.round(el));$('#o3').textContent='PKR '+num(Math.max(0,Math.round(pet-el)));$('#o4').textContent='PKR '+num(Math.max(0,Math.round((pet-el)*12)));$('#cs').href='contact.html?model='+encodeURIComponent(c.p.n)}
 $$('#dk,#cp,#ck,#cu,#cr',box).forEach(function(e){e.oninput=upd});$('#cm').onchange=function(){setR();upd()};setR();upd()}
function io(){var ob=new IntersectionObserver(function(es){es.forEach(function(e){if(e.isIntersecting)e.target.classList.add('in')})},{threshold:.12});$$('.rv').forEach(function(e){ob.observe(e)})}
if(pg==='home'){var hk=Y.hero.map(function(i){return by[i]}),all=P,keys=all.map(function(p){return p.imgs[0]});
 var hs=$('#hstage');if(hs&&window.YAD3D){var hv=YAD3D.viewer(hs,hk.map(function(p){return p.imgs[0]}),{scroll:1}),hi=0;
  var hset=function(i){hi=(i+hk.length)%hk.length;if(hv)hv.show(hi);var p=hk[hi];$('#hname').textContent=p.n;$('#hprice').textContent=pr(p);$('#hlink').href='product.html?id='+p.id};
  $('#hp').onclick=function(){hset(hi-1)};$('#hn').onclick=function(){hset(hi+1)};setInterval(function(){if(!document.hidden)hset(hi+1)},5200);hset(0)}
 $('#n1').textContent=P.length;
 $('#tabs').innerHTML=all.map(function(p,i){return '<button class="chip'+(i?'':' on')+'" data-i="'+i+'">'+p.short+'</button>'}).join('');
 function stats(p){var c=[['Top Speed',find(p,'Top speed')],['Range',find(p,'Range')],['Capacity',vv(p,'Battery').split(' / ').pop()],['Motor',vv(p,'Motor').split(' / ').pop()],['Price',pr(p)]];p.ex.forEach(function(r){c.push([r[0],r[1]])});return c.filter(function(x){return x[1]}).slice(0,3)}
 function xp(i){var p=all[i];$('#xp').dataset.i=i;$('#xinfo').innerHTML='<div class="tag">'+p.series+'</div><h3>'+p.n+'</h3><div class="tagl">'+(Y.tag[p.series]||'')+'</div><p>'+p.d+'</p><div class="xs">'+stats(p).map(function(x){return '<div><b>'+x[1]+'</b><span>'+x[0]+'</span></div>'}).join('')+'</div><a class="btn" href="product.html?id='+p.id+'">Learn more</a><a class="btn g" href="compare.html?a='+p.id+'">Comparison</a>'}
 $('#xp').innerHTML='<div class="stage v3" id="xst"><img class="fb" src="images/p/'+keys[0]+'.webp" alt="" style="inset:0;width:100%;height:100%"><div class="hint">Drag to rotate</div></div><div id="xinfo"></div>';
 var xv=window.YAD3D?YAD3D.viewer($('#xst'),keys,{}):null;xp(0);
 $$('#tabs .chip').forEach(function(c){c.onclick=function(){$$('#tabs .chip').forEach(function(x){x.classList.toggle('on',x===c)});if(xv)xv.show(+c.dataset.i);xp(+c.dataset.i)}});
 calc($('#calcbox'),by['yad-x9'])}
if(pg==='shop'){var cat=QS.get('cat')||'All',ser=QS.get('series')||'All',g=$('#pgrid');g.innerHTML=P.map(card).join('');
 $('#chips').innerHTML=['All'].concat(Y.cats).map(function(c){return '<button class="chip'+(c===cat?' on':'')+'" data-c="'+c+'">'+c+'</button>'}).join('');
 var sl=['All'];P.forEach(function(p){if(sl.indexOf(p.series)<0)sl.push(p.series)});$('#schips').innerHTML=sl.map(function(c){return '<button class="chip s'+(c===ser?' on':'')+'" data-s="'+c+'">'+c+'</button>'}).join('');
 var fs=$('#fsearch'),fo=$('#fsort');function filt(){var q=fs.value.toLowerCase(),cs=$$('.pc',g);cs.forEach(function(c){c.style.display=(cat==='All'||c.dataset.cat===cat)&&(ser==='All'||c.dataset.series===ser)&&c.dataset.name.indexOf(q)>-1?'':'none'});
  if(fo.value!=='0')cs.sort(function(a,b){return fo.value==='1'?a.dataset.price-b.dataset.price:b.dataset.price-a.dataset.price}).forEach(function(c){g.appendChild(c)});$('#cnt').textContent=cs.filter(function(c){return c.style.display!=='none'}).length+' models'}
 $$('#chips .chip').forEach(function(c){c.onclick=function(){cat=c.dataset.c;ser='All';$$('#chips .chip').forEach(function(x){x.classList.toggle('on',x===c)});$$('#schips .chip').forEach(function(x){x.classList.toggle('on',x.dataset.s==='All')});filt()}});
 $$('#schips .chip').forEach(function(c){c.onclick=function(){ser=c.dataset.s;cat='All';$$('#schips .chip').forEach(function(x){x.classList.toggle('on',x===c)});$$('#chips .chip').forEach(function(x){x.classList.toggle('on',x.dataset.c==='All')});filt()}});fs.oninput=filt;fo.onchange=filt;filt()}
if(pg==='product'){var p=by[QS.get('id')]||P[0];document.title=p.n+' | YAD Electric Vehicles';var md=$('meta[name=description]');if(md)md.content=p.n+' – '+p.d;var cn=$('link[rel=canonical]');if(cn)cn.href='https://www.yadebikes.com/product.html?id='+p.id;
 var th=p.imgs.length>1?'<div class="th">'+p.imgs.map(function(k,i){return '<img class="'+(i?'':'on')+'" src="images/p/'+k+'.webp" alt="'+p.n+'">'}).join('')+'</div>':'';
 var gm='<div class="stage v3 pst" id="pv3"><img class="fb" src="images/p/'+p.imgs[0]+'.webp" alt="'+p.n+'" style="inset:0;width:100%;height:100%"><div class="hint">Drag to rotate</div></div>'+th;
 var msg=minp(p)?'Assalam o Alaikum YAD, I want to order '+p.n+' ('+pr(p)+'). Please confirm availability.':'Assalam o Alaikum YAD, please share price and details of '+p.n+'.';
 var c=[['Top Speed',find(p,'Top speed')],['Range',find(p,'Range')],['Capacity',vv(p,'Battery').split(' / ').pop()],['Motor',vv(p,'Motor').split(' / ').pop()]];p.ex.forEach(function(r){c.push([r[0],r[1]])});var st=c.filter(function(x){return x[1]}).slice(0,3);
 var n=p.vars.length,cols='minmax(110px,.8fr) repeat('+n+',minmax(0,1fr))',rows='';
 if(p.vars[0].bat){rows+='<div class="spt" style="grid-template-columns:'+cols+'"><div></div>'+p.vars.map(function(v){return '<div class="h">'+v.n+'</div>'}).join('');
  [['Price','pr'],['Battery','bat'],['Motor','mot']].forEach(function(k){rows+='<div class="k">'+k[0]+'</div>'+p.vars.map(function(v){return '<div class="v">'+(k[1]==='pr'?(v.pr?fm(v.pr):'On request'):v[k[1]])+'</div>'}).join('')});rows+='</div>'}
 rows+='<div class="spt" style="grid-template-columns:minmax(110px,.8fr) 2fr;margin-top:8px">'+p.ex.map(function(r){return '<div class="k">'+r[0]+'</div><div class="v">'+r[1]+'</div>'}).join('')+'<div class="k">Colours</div><div class="v">'+sw(p)+'</div></div>';
 var rel=P.filter(function(q){return q.id!==p.id&&q.cat===p.cat}).concat(P.filter(function(q){return q.cat!==p.cat})).slice(0,4);
 $('#pbox').innerHTML='<section class="phero"><div class="wrap"><div class="crumb"><a href="index.html">Home</a> / <a href="shop.html">Models</a> / '+p.n+'</div><div class="tag">'+p.series+'</div><h1 class="ptitle">'+p.n+'</h1><div class="tagl">'+(Y.tag[p.series]||'')+'</div>'+gm+'<div class="stats3">'+st.map(function(s){return '<div><b>'+s[1]+'</b><span>'+s[0]+'</span></div>'}).join('')+'<div><b>'+pr(p)+'</b><span>Price</span></div></div><div class="pcta"><a class="btn" target="_blank" rel="noopener" href="'+wl(msg)+'">'+WAI+(minp(p)?'Order on WhatsApp':'Ask for price')+'</a><a class="btn g" href="contact.html?model='+encodeURIComponent(p.n)+'">Schedule a ride</a><a class="btn g" href="compare.html?a='+p.id+'">Comparison</a></div></div></section>'+
 '<section class="sec alt"><div class="wrap"><div class="tag">About this model</div><h2>'+p.n+'</h2><p>'+p.d+'</p></div></section>'+
 (p.vars[0].bat?'<section class="sec"><div class="wrap" id="calcbox"></div></section>':'')+
 '<section class="sec alt"><div class="wrap"><div class="tag">Specification</div><h2>Model specification</h2>'+rows+'<p class="note">Prices as per YAD price list effective 05 May 2026. Contact us to confirm availability.</p></div></section>'+
 '<section class="sec"><div class="wrap"><h2>You may also like</h2><div class="grid">'+rel.map(card).join('')+'</div></div></section>';
 if(p.vars[0].bat)calc($('#calcbox'),p);
 var s=document.createElement('script');s.type='application/ld+json';s.textContent=JSON.stringify({'@context':'https://schema.org','@type':'Product',name:p.n,description:p.d,brand:{'@type':'Brand',name:'YAD'},offers:minp(p)?{'@type':'AggregateOffer',priceCurrency:'PKR',lowPrice:minp(p)}:undefined});document.head.appendChild(s);
 var pv=$('#pv3');if(window.YAD3D){var v=YAD3D.viewer(pv,p.imgs,{});$$('.th img').forEach(function(t,i){t.onclick=function(){if(v)v.show(i);$$('.th img').forEach(function(x){x.classList.toggle('on',x===t)})}})}}
if(pg==='compare'){var ids=[QS.get('a'),QS.get('b'),QS.get('c')],opt=function(sel){return '<option value="">— none —</option>'+P.map(function(p){return '<option value="'+p.id+'"'+(p.id===sel?' selected':'')+'>'+p.n+'</option>'}).join('')};
 $('#csel').innerHTML=[0,1,2].map(function(i){var def=ids[i]||(i<2?P[i*2].id:'');return '<select data-i="'+i+'">'+opt(def)+'</select>'}).join('');
 function rc(){var sel=$$('#csel select').map(function(s){return by[s.value]}).filter(Boolean),rows=['Price','Battery','Motor','Top speed','Range','Brakes','Lights','Tyres','Warranty'];
  $('#ctab').innerHTML='<div class="cg" style="grid-template-columns:140px repeat('+sel.length+',minmax(0,1fr))"><div></div>'+sel.map(function(p){return '<div class="ch"><img src="'+(p.imgs.length?'images/p/'+p.imgs[0]+'.webp':'images/placeholder.svg')+'" alt=""><h3>'+p.n+'</h3><a class="tag" href="product.html?id='+p.id+'">View →</a></div>'}).join('')+rows.map(function(r){return '<div class="rl">'+r+'</div>'+sel.map(function(p){return '<div class="rv2">'+(find(p,r)||'—')+'</div>'}).join('')}).join('')+'</div>'}
 $$('#csel select').forEach(function(s){s.onchange=rc});rc()}
if(pg==='contact'){$('#model').innerHTML='<option>Not sure yet</option>'+P.map(function(p){return '<option>'+p.n+'</option>'}).join('');var pre=QS.get('model');if(pre)$('#model').value=pre;var pu=QS.get('purpose');if(pu)$('#purpose').value=pu;var cf=$('#contactForm');function val(n){return (cf.elements[n].value||'').trim()}
 cf.onsubmit=function(e){e.preventDefault();location.href=wl('*Website enquiry*\nName: '+val('name')+'\nPhone: '+val('phone')+'\nEmail: '+val('email')+'\nCity: '+val('city')+'\nInterested in: '+val('model')+'\nPurpose: '+val('purpose')+'\n\nMessage: '+val('message'))}}
io();
})();
